#!/bin/sh
if [ ! -n "$1" ] ;then
    echo "please input deploy message"
    exit 0
else
    git add .
    git commit -m "$1"
    git push
fi

USER=fliaping
HOST=blog
DIR=www/fliaping_blog   # might sometimes be empty!

# hugo && rsync -avzhu --delete public/ ${USER}@${HOST}:~/${DIR}
rm -rf ~/.qshell/qupload
hugo && qshell qupload2 --bucket www-blog --src-dir ./public --overwrite --thread-count 5 --rescan-local
qshell cdnrefresh -r -i ./qiniu_refresh.txt
exit 0