#!/bin/bash
if [ ! -n "$1" ] ;then
    echo "please input deploy message"
    exit 0
else
    ./upload_and_replace.sh
    git add .
    git commit -m "$1"
    git push
fi

USER=fliaping
HOST=blog
DIR=www/fliaping_blog   # might sometimes be empty!

# hugo && rsync -avzhu --delete public/ ${USER}@${HOST}:~/${DIR}
# rm -rf ~/.qshell/qupload
hugo && \
ossutil --config-file ~/.ossconfig cp -r ./public oss://fliaping-blog -u && \
ossutil --config-file ~/.ossconfig cp -r ./storage oss://fliaping-blog/storage -u
# qshell qupload2 --bucket www-blog --src-dir ./public --overwrite --thread-count 5 --rescan-local
# qshell cdnrefresh -r -i ./qiniu_refresh.txt
exit 0