#!/bin/sh
if [ ! -n "$1" ] ;then
    echo "please input deploy message"
    exit 0
else
    git commit -m "$1"
fi

# USER=fliaping
# HOST=june
# DIR=www/fliaping_blog   # might sometimes be empty!

# hugo && rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR}

# exit 0